# Ref. http://about.travis-ci.org/docs/user/languages/python/
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
install:
  - if [[ $TRAVIS_PYTHON_VERSION < '2.6' ]]; then pip install --use-mirrors simplejson PyYAML pep8 pylint flake8 Jinja2; else pip install --use-mirrors PyYAML pep8 pylint flake8 Jinja2; fi
env:
  - WITH_COVERAGE=1
script:
  - "./pkg/runtest.sh"
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - satoru.satoh+github@gmail.com
    on_failure: always
