# Ref. http://about.travis-ci.org/docs/user/languages/python/
language: python
python:
  - 2.6
  - 2.7
# - 3.2
  - 3.3
install:
  - if [[ $TRAVIS_PYTHON_VERSION < '2.6' ]]; then pip install --use-mirrors simplejson PyYAML pep8 pylint flake8 Jinja2; else pip install --use-mirrors PyYAML pep8 pylint flake8 Jinja2; fi
script:
  - "./aux/runtest.sh"
notifications:
  email:
    on_failure: always
