# Ref. http://about.travis-ci.org/docs/user/languages/python/
language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
install:
    - pip install --use-mirrors anyconfig jinja2 pep8
script:
    - "./tests/runtest.sh"
