# Ref. http://about.travis-ci.org/docs/user/languages/python/
language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
#matrix:
#    include:
#        - python: 2.4
#          env: FULL="true"
#        - python: 2.5
#          env: FULL="true"
#        - python: 2.6
#          env: FULL="true"
#        - python: 2.7
#          env: FULL="true"
##        - python: 3.2
##          env: LANG="en_US.utf-8"
install:
    - pip install --use-mirrors anyconfig jinja2 pep8
script:
    - "./tests/runtest.sh"
